spring:
    profiles:
      active: prod

    thymeleaf:
       cache: false 
       prefix: classpath:/templates/
       encoding: UTF-8
       suffix: .html
       mode: LEGACYHTML5
    datasource:
       driver-Class-Name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/mydata?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
       username: root
       password: lmz760923

logging:
     config: classpath:logback.xml
 